use_frameworks!

# platform :ios, '9.0'

target 'qrframework_part_5_Example' do
  pod 'qrframework_part_5', :path => '../'

  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'Fabric'
  pod 'MaterialComponents/Snackbar'
  pod 'Crashlytics', '~>  3.10'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'MoEngage-iOS-SDK' , '~>7.0.4'
  pod 'MOGeofence' , '~>3.0.1'
  pod 'MoEngageInApp','~> 2.0.0'
  pod 'SVProgressHUD'
  pod 'MYPassthrough'
  pod 'Sejima'
  pod 'AppsFlyerFramework'
  pod 'lottie-ios'
  pod 'Alamofire'
  # pod 'SDWebImage'
  pod 'SkeletonView'

  #guntur
  pod 'TTSegmentedControl', '~>0.4.9'

  #refactor
  pod 'RxSwift'
  target 'qrframework_part_5_Tests' do
    inherit! :search_paths

    
  end
end
